### ISSUE TITLE
Encode is broken

### ISSUE THREAD

**Issue by tsatke** [alexflint/go-memdump#4]
https://play.golang.org/p/kgtlXR1qaSG

Is this intended behaviour? Am I using it wrong?

**Comment by TheApeMachine** [comment]
> https://play.golang.org/p/kgtlXR1qaSG
> 
> Is this intended behaviour? Am I using it wrong?

You indeed were using it wrong: https://go.dev/play/p/7rOgLpW7Vie

**Comment by alexflint** [comment]
Yeah as @TheApeMachine said, I think you were using it wrong, but here is how I believe the code should look:
```go
package main

import (
	"bytes"
	"fmt"

	memdump "github.com/alexflint/go-memdump"
)

func main() {
	foo := Foo{
		Bar{"Hello"},
		Bar{"World"},
	}
	fmt.Printf("foo: %#v\n", foo)

	buf := bytes.NewBuffer([]byte{})
	memdump.Encode(buf, &foo)

	var baz *Foo
	memdump.Decode(buf, &baz)
	fmt.Printf("baz: %#v\n", *baz)
}

type Foo struct {
	bar Bar
	sna Bar
}

type Bar struct {
	content string
}
```
Output:
```
foo: main.Foo{bar:main.Bar{content:"Hello"}, sna:main.Bar{content:"World"}}
baz: main.Foo{bar:main.Bar{content:"Hello"}, sna:main.Bar{content:"World"}}
```

I know it's a little strange to give it a pointer to a pointer. The reason for that is that memdump loads the entire buffer into a single continguous chunk of memory, adjusts some values within that chunk that correspond to other addresses within the chunk, then stores a pointer to the first byte in the chunk in the pointer that you pass in to Decode. It's actually not possible to do that with a pointer to a struct because the struct has already been allocated and there is no more contiguous memory at the end of the struct. Just for your interest!

**Comment by tsatke** [comment]
Thanks for the explanation!
